### ISSUE TITLE
Linked twitter thread is missing a participant 

### ISSUE THREAD

**Issue by thomasjpfan** [pypackaging-native/pypackaging-native#1]
The linked twitter thread:

https://github.com/pypackaging-native/pypackaging-native/blob/782d42d7fe6c9b67e604f1864b56f11ca2f6254a/docs/meta-topics/purposes_of_pypi.md?plain=1#L161-L162

is missing one of the participants because the account was deleted. It's likely still useful to include, but some context could be missing.

**Comment by fingolfin** [comment]
Some (?) of the tweets can be see on the Internet archive, see https://web.archive.org/web/20210714223813/https://twitter.com/zooba/status/1415440484181417998

**Comment by rgommers** [comment]
Thanks @fingolfin, that is helpful. Linking to that in addition to the original thread should close this issue I think.
