### ISSUE TITLE
Add more clear guidance about what gets discussed where

### ISSUE THREAD

**Issue by rgommers** [pypackaging-native/pypackaging-native#14]
For discussing content on the site, it's GitHub. What is less obvious than it should be is that the primary venue for discussing potential solutions is https://discuss.python.org (thanks for asking @bskinn!) - add that to the front page and the README in this repo.

**Comment by NickleDave** [comment]
Would it be worth linking previous topics on there (to maybe help avoid rehashing discussions)?
e.g., https://discuss.python.org/t/wanting-a-singular-packaging-tool-vision/21141/1

**Comment by bskinn** [comment]
> Would it be worth linking previous topics on there (to maybe help avoid rehashing discussions)? e.g., https://discuss.python.org/t/wanting-a-singular-packaging-tool-vision/21141/1

I thought of this, but then it opens the can of worms of the maintenance burden of keeping it up to date.

Would need to frame it as a community effort from the outset, perhaps?

**Comment by NickleDave** [comment]
Understood.

Could possibly provide a `{note}` that says something like: "here are some previous threads to capture discussion, it is not meant to be a complete up-to-date list" 

but totally get why you would not want to maintain a list of discuss topics

**Comment by rgommers** [comment]
Those kinds of monster threads don't happen all the time, so as long as it's phrased as a reference to a previous discussion rather than an encouragement to continue appending to the thread, I think it'd be fine to maintain a list. That's after all done in a number of places. This is supposed to be a living and up-to-date reference, so why not here I'd say.
