### ISSUE TITLE
Consider BLAS/LAPACK demuxing libraries

### ISSUE THREAD

**Issue by giordano** [pypackaging-native/pypackaging-native#18]
The page [BLAS, LAPACK and OpenMP](https://pypackaging-native.github.io/key-issues/native-dependencies/blas_openmp/) could mention BLAS/LAPACK demuxing libraries, like [FlexiBLAS](https://www.mpi-magdeburg.mpg.de/projects/flexiblas) and [libblastrampoline](https://github.com/JuliaLinearAlgebra/libblastrampoline).

**Comment by h-vetinari** [comment]
conda-forge also offers a way to transparently switch between BLAS/LAPCK implementations; however, it can only have one different flavour (netlib, openblas, mkl, blis) at runtime. libblastrampoline looks interesting, in particular:
> ## ABI standard
> 
> `libblastrampoline` exports a consistent ABI for applications to link against. In particular, we export both a 32-bit (LP64) and 64-bit (ILP64) interface, allowing applications that use one or the other (or both!) to link against the library.

**Comment by rgommers** [comment]
Good point, I'll mention both of those. SciPy's `cython_blas`/`cython_lapack` is also effectively that kind of demuxer for downstream Python packages, it provides the same kind of ABI wrapping.

One challenge we have is that we can add support for Flexiblas, but we can't guarantee its usage (plus there'd be a license problem - see https://github.com/scipy/scipy/issues/17362). Given that Python packages have to be built in all sorts of distros which have their own approaches, and Pip & co also support building from source against any installed library, it's just an extra option. 

What conda-forge does is already explained.
