### ISSUE TITLE
Another package manger serving binary artifacts for different ISAs: Pkg.jl

### ISSUE THREAD

**Issue by giordano** [pypackaging-native/pypackaging-native#19]
[Distributing a package containing SIMD code](https://pypackaging-native.github.io/key-issues/simd_support/) says Spack is an exception among package managers in serving binaries for different ISAs.  Even though Spack nowdays has a build cache, it's mainly focused on doing local builds, so in a sense it follows strategy (1) of targeting a single SIMD architecture: the one of the current system.

However there is at least another package manager which can serve binaries for different ISAs (and it doesn't do local builds, it only serves prebuilt binaries): Julia's [Pkg.jl](https://github.com/JuliaLang/Pkg.jl/).  As an example, see [`finufft_jll.jl`](https://github.com/JuliaBinaryWrappers/finufft_jll.jl), which has been built for different x86_64 ISAs (generic, avx, avx2, avx512).  However I should mention that support for managing multiple ISAs in the Julia ecosystem isn't fully fledged yet, there are a couple of issues to fix and decisions to take, but the basic infrastructure is there and it's working.

I appreciate this isn't related to the Python ecosystem, I don't know whether you want to mention it in this website, but I figured I'd mention it in case you want to add for completeness as reference.

**Comment by rgommers** [comment]
Thanks @giordano, that is quite interesting. I do want to mention `Pkg.jl` and that it can do this. Even though it can't be used for Python packages, it's helpful to have a good overview of the state of the art for every topic.

**Comment by giordano** [comment]
Oh yes, I opened a few issues here, but I should also have mentioned that I quite enjoyed reading the information on the website, it's a topic I'm interested in and I think it's great you took the time to put this stuff together!

**Comment by rgommers** [comment]
Thanks @fingolfin and @giordano, great to hear it's of interest beyond Python.
