### ISSUE TITLE
How much would a "draft" state for package releases help with coordination?

### ISSUE THREAD

**Issue by pradyunsg** [pypackaging-native/pypackaging-native#20]
From https://pypackaging-native.github.io/meta-topics/pypi_social_model/:

> It's difficult to do anything that requires coordination across projects.

What if PyPI releases had a "draft" state where they'd be available on a specific index URL that you could use _in addition_ to the regular index URL of pypi.org? That doesn't solve the need for co-ordination but it would make it easier.

x-ref https://github.com/pypi/warehouse/issues/726 (where I also just posted a comment)

**Comment by h-vetinari** [comment]
I think it's less "could you try if this works for you" coordination that's difficult (people can publish alpha/beta/rcs), and more the "can we agree to all {compile against the same ABI of `libfoo`, use the same compiler flags, etc.}" .

It's less of an infrastructure/testing issue, and more a social issue who can decide & enforce such standards. For a distribution there's an extra layer that takes care of this, but on PyPI it's more like herding cats. I guess it's conceivable that PyPI defines an "ingress check" that needs to pass for packages to be published, but that goes in the opposite direction (more curation) compared to adding a draft state.

**Comment by rgommers** [comment]
Thanks @pradyunsg and @h-vetinari. I think you both make valid points. Having a draft state would be potentially useful, it allowing synchronized releases - so I'd be in favor of PyPI adding it. In the overall coordination issue it's a lot less important though than the herding cats and "who decides" thing.

**Comment by rgommers** [comment]
After reading through https://github.com/pypi/warehouse/issues/726, I think it's useful to link that under potential solutions/mitigations as a step in the right direction.
