### ISSUE TITLE
Remove paragraph about extensions built with release builds are not compatible with debug builds

### ISSUE THREAD

**Issue by isuruf** [pypackaging-native/pypackaging-native#28]
> As an example of an ABI issue that many Python developers will encounter: a debug build of CPython is not ABI-compatible with a release build, hence if one wants to use a debug Python, one has to rebuild every package that uses the Python C API.

This is simply not true. The other way around is true. If you build an extension module with a debug build it is not compatible with a release build.

**Comment by rgommers** [comment]
Thanks for catching that @isuruf! I'll fix that text soon.

**Comment by rgommers** [comment]
Removed now. Even the reverse is mostly no longer true. From https://docs.python.org/3/using/configure.html#python-debug-build:

Changed in version 3.8: Release builds and debug builds are now ABI compatible: defining the `Py_DEBUG` macro no longer implies the `Py_TRACE_REFS` macro (see the [`--with-trace-refs`](https://docs.python.org/3/using/configure.html#cmdoption-with-trace-refs) option), which introduces the only ABI incompatibility.
