### ISSUE TITLE
Mention crossenv somewhere for cross-compilation

### ISSUE THREAD

**Issue by virtuald** [pypackaging-native/pypackaging-native#31]
I don't have time to contribute at the moment, but I came across the pypackaging-native site and found it useful, thanks!

I've found the [crossenv](https://crossenv.readthedocs.io/en/latest/) tool to be really useful for doing cross-compilation, and it deserves a mention here somewhere. There is a discourse thread about crossenv here: https://discuss.python.org/t/towards-standardizing-cross-compiling/10357

**Comment by rgommers** [comment]
Thanks @virtuald! gh-27 happens to already have content on cross-compiling and does indeed mention `crossenv`.

**Comment by rgommers** [comment]
This is done now: https://pypackaging-native.github.io/key-issues/cross_compilation/
