### ISSUE TITLE
Improve the GPU page

### ISSUE THREAD

**Issue by leofang** [pypackaging-native/pypackaging-native#35]
Right now, the key issue titled "Packaging projects with GPU code" has quite some issues. Discussed offline with @rgommers a while back, and very recently with @shwina @vyasr. One of us will send a draft PR as a basis for us to iterate on it.

**Comment by rgommers** [comment]
Thanks @leofang. Apologies for the wrapping my head around the details of this. The write-up in https://github.com/NVIDIA/cuQuantum/tree/main/extra/demo_build_with_wheels is quite helpful, but I don't deal with GPU packaging on a daily basis. A draft PR to get the ball rolling from one of you would be great.

**Comment by leofang** [comment]
Closed by #36.
