### ISSUE TITLE
Proposal: Merge the whole website into packaging.python.org

### ISSUE THREAD

**Issue by viblo** [pypackaging-native/pypackaging-native#44]
Hello! 

So, a couple of weeks back I was looking for info around how to handle SIMD-code but couldnt find any, until I opened an issue https://github.com/pypa/packaging-problems/issues/759 and got directed here. As I wrote in the issue-thread, the packaging-native site contained exactly what I was looking for, very nice. 

However, I wonder.. Is there a special reason this is separate project from the overall pypa/packaging.python.org project? Now, I do not expect to contribute anything of value myself, but maybe I can still be a bit bold and suggest this project would benefit from being merged into the general packaging project? At least from the reader's point of view they very much are the same and it would help discovery.

**Comment by rgommers** [comment]
Hi @viblo, thanks for the feedback and question.  

> Is there a special reason this is separate project from the overall pypa/packaging.python.org project? 

The key reason is that the goals and audiences are different. The Python Packaging User Guide focuses on the _users_ of packaging tools and specs, while this project focuses on the _developers_ of such tooling and specs. From the front page: _"The content on this site is meant to provide insights and good reference material. This will hopefully provide common ground when discussing potential solutions for those problems or design changes in Python packaging as a whole or in individual packaging tools."_

Ideally sections of https://pypackaging-native.github.io/ can be retired or moved into other documentation (the packaging user guide, PEPs, docs of individual tools, etc.) as solutions start to materialize.

Beyond that, the review process on the packaging user guide is, to put it mildly, suboptimal. So also from that perspective, I don't think this merge would be possible.

**Comment by viblo** [comment]
Thanks for the reply! I do think that while this site focus more on developers, its still useful those like me that want to package a slightly more advanced project with native code with the current state of the packaging user guide. 

I saw you found my PR there to at least link to here, which I think is the most important. If the content itself is separate or not is not so important as long as its easy to find. 

Anyway, given you feel the process around the user guide suboptimal I agree with you, better to keep these sites separate, anything that can reduce friction to actually improve packaging is good!

**Comment by rgommers** [comment]
> I saw you found my PR there to at least link to here, which I think is the most important. If the content itself is separate or not is not so important as long as its easy to find.

+1 for this. Thanks for helping add a cross-link.
